version: '3'

services:
  web:
    build: .
    container_name: bms
    
    restart: always
    volumes:
      - .:/django-blood-bank-management-system
    ports:
      - "8020:8000"
    depends_on:
      - db
    command: "sh run.sh"    
    env_file:
      - .env

  db:
    image: postgres:15
    container_name: db
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres  # Match your Django DB_NAME
      POSTGRES_USER: postgres  # Match your Django DB_USER
      POSTGRES_PASSWORD: postgres  # Match your Django DB_PASSWORD

