# Generated by Django 5.1 on 2024-08-11 12:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0014_user_age_user_blood_group_user_gender_user_illness_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodDonationCenter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID')),
                ('metadata', models.JSONField(blank=True, default=dict, null=True, verbose_name='meta data')),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True, verbose_name='Is Deleted')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Time Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Time Modified')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('contact_number', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID')),
                ('metadata', models.JSONField(blank=True, default=dict, null=True, verbose_name='meta data')),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True, verbose_name='Is Deleted')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Time Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Time Modified')),
                ('appointment_date', models.DateTimeField()),
                ('status', models.CharField(choices=[("('scheduled', 'Scheduled')", 'Schedule'), ("('completed', 'Completed')", 'Completed'), ("('cancelled', 'Cancelled')", 'Cancelled'), ("('pending', 'pending')", 'Pending')], default="('pending', 'pending')", max_length=50)),
                ('donor', models.ForeignKey(limit_choices_to={'user_type': 'donor'}, on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.blooddonationcenter')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID')),
                ('metadata', models.JSONField(blank=True, default=dict, null=True, verbose_name='meta data')),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True, verbose_name='Is Deleted')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Time Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Time Modified')),
                ('date', models.DateField()),
                ('volume', models.PositiveIntegerField()),
                ('blood_group', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=50, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('donor', models.ForeignKey(limit_choices_to={'user_type': 'donor'}, on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
