# Generated by Django 5.1 on 2024-08-12 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_donation_donor_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='center',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='donor',
        ),
        migrations.AddField(
            model_name='donation',
            name='status',
            field=models.CharField(choices=[("('scheduled', 'Scheduled')", 'Schedule'), ("('completed', 'Completed')", 'Completed'), ("('cancelled', 'Cancelled')", 'Cancelled'), ("('pending', 'pending')", 'Pending')], default="('pending', 'pending')", max_length=50, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[("('scheduled', 'Scheduled')", 'Schedule'), ("('completed', 'Completed')", 'Completed'), ("('cancelled', 'Cancelled')", 'Cancelled'), ("('pending', 'pending')", 'Pending')], default="('pending', 'pending')", max_length=50, verbose_name='Status'),
        ),
        migrations.DeleteModel(
            name='BloodDonationCenter',
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
