# Generated by Django 4.2.11 on 2024-10-14 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_blogpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='button',
            field=models.CharField(default='Read More', max_length=50),
        ),
    ]
